export interface Product {
  id: string
  sku: string
  name: string
  description: string
  category: "Flores Comestibles" | "Brotes" | "Hortalizas y Hojas Verdes"
  image: string
  usage?: string
  flavorProfile?: string
  price: number
  unitOfMeasure: string;
  collection?: "Primavera"|"Verano"|"Otoño"|"Invierno"|"Todo el año"
}

export const products: Product[] = [
  // --- FLORES COMESTIBLES (Actualizado con ítems faltantes) ---
  {
    id: "margarita-mini",
    sku: "FE-001",
    name: "Margarita Mini",
    description: "Delicadas y vibrantes, con un sutil sabor herbáceo y notas dulces.",
    usage: "Ideales para decorar postres, cócteles y ensaladas frescas.",
    category: "Flores Comestibles",
    image: "/placeholder.svg?height=400&width=400",
    price: 35,
    unitOfMeasure: "Domo",
    collection: "Primavera",
  },
  {
    id: "pensamiento-chico",
    sku: "FE-002",
    name: "Pensamiento Chico",
    description: "Pequeñas flores comestibles de colores vivos y sabor suave.",
    usage: "Ideales para decorar ensaladas, postres y cócteles, aportando un toque de elegancia y color.",
    category: "Flores Comestibles",
    image: "/flor_pensam_ch.jpg",
    price: 35,
    unitOfMeasure: "Domo",
    collection: "Primavera",
  },
  {
    id: "pensamiento-grande",
    sku: "FE-003",
    name: "Pensamiento Grande",
    description: "Flores más grandes con colores intensos. Sabor suave y ligeramente vegetal.",
    usage: "Adecuado para adornar platos principales, pasteles y ensaladas.",
    category: "Flores Comestibles",
    image: "/flor_pensam_g.jpg",
    price: 35,
    unitOfMeasure: "Domo",
    collection: "Primavera",
  },
  {
    id: "begonia-imperial",
    sku: "FE-004",
    name: "Begonia Imperial",
    description: "Llamativa y exótica, con pétalos jugosos y un sabor ácido con matices afrutados.",
    usage: "Perfecta para equilibrar ensaladas, decorar platillos gourmet o añadir un giro cítrico a los postres.",
    category: "Flores Comestibles",
    image: "/begonia_dragon.jpg",
    price: 35,
    unitOfMeasure: "Domo",
    collection: "Verano",
  },
  {
    id: "begonia-dragon",
    sku: "FE-005",
    name: "Begonia Dragón",
    description: "Sus pétalos carnosos tienen un sabor cítrico y refrescante con un toque ácido, similar al ruibarbo.",
    usage: "Perfectas para ensaladas, platillos frutales o simplemente como un acento decorativo.",
    category: "Flores Comestibles",
    image: "/edible-begonia-flower.jpg",
    price: 35,
    unitOfMeasure: "Domo",
    collection: "Primavera",
  },
  {
    id: "flor-miel-morada",
    sku: "FE-006",
    name: "Flor de Miel Morada",
    description: "Pequeñas flores con un aroma embriagador y un sabor dulce con matices herbáceos.",
    usage: "Ideales para infusionar en jarabes, postres y decorar platillos sofisticados.",
    category: "Flores Comestibles",
    image: "/flor_miel_m.jpg",
    price: 35,
    unitOfMeasure: "Domo",
    collection: "Invierno",
  },
  {
    id: "flor-miel-blanca",
    sku: "FE-007",
    name: "Flor de Miel Blanca",
    description: "Similar a su versión morada, pero con un perfil más delicado y floral.",
    usage: "Se usa para aromatizar bebidas, decorar postres y dar un toque sutil a ensaladas.",
    category: "Flores Comestibles",
    image: "/flor_miel.jpg",
    price: 35,
    unitOfMeasure: "Domo",
    collection: "Primavera",
  },
  {
    id: "calendula",
    name: "Caléndula",
    sku: "FE-008",
    description: "Pétalos de color vibrante y un sabor ligeramente picante y cítrico.",
    usage: "Se utilizan en ensaladas, arroces y sopas para aportar un toque de color y frescura.",
    category: "Flores Comestibles",
    image: "/calendula.jpg",
    price: 35,
    unitOfMeasure: "Domo",
    collection: "Primavera",
  },
  {
    id: "petalos-rosa",
    name: "Pétalos de Rosa",
    sku: "FE-009",
    description: "Suaves y perfumados, con un sutil dulzor floral.",
    usage: "Ideales para infusiones, mermeladas, postres y decoraciones elegantes.",
    category: "Flores Comestibles",
    image: "/placeholder.svg",
    price: 35,
    unitOfMeasure: "Domo",
    collection: "Primavera",
  },
  {
    id: "violas-amarillas",
    sku: "FE-010",
    name: "Violas Amarillas",
    description: "Pequeñas y vistosas, con un sabor suave y ligeramente terroso.",
    usage: "Aportan un toque alegre a ensaladas, bebidas y postres.",
    category: "Flores Comestibles",
    image: "/placeholder.svg?height=400&width=400",
    price: 35,
    unitOfMeasure: "Domo",
    collection: "Primavera",
  },
  {
    id: "violas-moradas",
    name: "Violas Moradas",
    sku: "FE-011",
    description: "Con un sabor delicado y matices florales.",
    usage: "Ideales para embellecer cualquier platillo sin sobrecargar su sabor.",
    category: "Flores Comestibles",
    image: "/placeholder.svg?height=400&width=400",
    price: 35,
    unitOfMeasure: "Domo",
    collection: "Primavera",
  },
  {
    id: "crisantemos",
 sku: "FE-012",
 collection: "Verano",
    name: "Crisantemos",
    description: "Pétalos llamativos y un sabor ligeramente amargo con toques especiados.",
    usage: "Se utilizan en infusiones, ensaladas y guisos asiáticos para aportar profundidad y aroma.",
    category: "Flores Comestibles",
    image: "/crisantemo.jpg",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "lavanda",
 sku: "FE-013",
 collection: "Primavera",
    name: "Lavanda",
    description: "Aromática y delicada, con notas florales y herbales.",
    usage: "Perfecta para infusiones, repostería y platillos sofisticados.",
    category: "Flores Comestibles",
    image: "/single-lavender-stem.png",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "flor-cilantro",
 sku: "FE-014",
 collection: "Primavera",
    name: "Flor de Cilantro",
    description: "Sabor suave y fresco con un ligero toque a cilantro.",
    usage: "Ideal para decorar sopas, ceviches y ensaladas.",
    category: "Flores Comestibles",
    image: "/cilantro-flower.jpg",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "flor-hinojo",
 sku: "FE-015",
 collection: "Primavera",
    name: "Flor de Hinojo",
    description: "Aromática y ligeramente anisada.",
    usage: "Perfecta para pescados, carnes y postres.",
    category: "Flores Comestibles",
    image: "/fennel-flower.jpg",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "clavelina",
 sku: "FE-016",
 collection: "Primavera",
    name: "Clavelina",
    description: "Pétalos coloridos con un toque especiado y sutilmente dulce. Ideales para repostería y bebidas.",
    usage: "Ideales para repostería y bebidas.",
    category: "Flores Comestibles",
    image: "/dianthus-flower.jpg",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "flor-sauco",
 sku: "FE-017",
 collection: "Verano",
    name: "Flor de Sauco",
    description: "Notas florales y dulces con un toque cítrico.",
    usage: "Excelente para jarabes, infusiones y cócteles.",
    category: "Flores Comestibles",
    image: "/elderflower.jpg",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "bugambilia",
 sku: "FE-018",
 collection: "Verano",
    name: "Flor de Bugambilia",
    description: "Pétalos vibrantes con un toque terroso y herbal.",
    usage: "Tradicional en infusiones y decoraciones.",
    category: "Flores Comestibles",
    image: "/bougainvillea-flower.jpg",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "aretillos",
 sku: "FE-019",
 collection: "Verano",
    name: "Flores Aretillos",
    description: "Flores llamativas con notas florales y un ligero dulzor.",
    usage: "Ideales para platos gourmet.",
    category: "Flores Comestibles",
    image: "/fuchsia-flower.jpg",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "capuchina",
 sku: "FE-020",
 collection: "Verano",
    name: "Flor Capuchina",
    description: "Pétalos de colores vivos con un sabor picante similar al rábano.",
    usage: "Ideales para ensaladas y platos frescos.",
    category: "Flores Comestibles",
    image: "/single-nasturtium.png",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "rosas-miniatura",
 sku: "FE-021",
 collection: "Primavera",
    name: "Rosas Miniatura",
    description: "Elegantes y aromáticas, con un delicado sabor floral.",
    usage: "Usadas en repostería, infusiones y platos gourmet.",
    category: "Flores Comestibles",
    image: "/rosa_mini.jpg",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "borraja",
 sku: "FE-022",
 collection: "Verano",
    name: "Flor de Borraja",
    description: "Azules y delicadas, con un ligero sabor a pepino.",
    usage: "Perfectas para ensaladas y bebidas refrescantes.",
    category: "Flores Comestibles",
    image: "/borage-flower.jpg",
    price: 35,
    unitOfMeasure: "Domo",
  },

  // --- BROTES (AÑADIDOS) ---
  {
    id: "brote-mostaza",
 sku: "BH-001",
 collection: "Otoño",
    name: "Brote de Mostaza",
    description: "Hojas pequeñas con un sabor picante y ligeramente amargo, que recuerdan a la mostaza en su versión más fresca.",
    usage: "Ideales para ensaladas, sándwiches y platos asiáticos.",
    category: "Brotes",
    image: "/brote_mostaza.jpg",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "brote-apio",
 sku: "BH-002",
 collection: "Verano",
    name: "Brote de Apio",
    description: "Brote del apio con un sabor más suave y notas herbáceas.",
    usage: "Aporta frescura a ensaladas, sopas y guarniciones.",
    category: "Brotes",
    image: "/brote_apio.jpg",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "brote-col-morada",
 sku: "BH-003",
 collection: "Verano",
    name: "Brote de Col Morada",
    description: "Pequeñas hojas de un vibrante tono púrpura, con un sabor suave y ligeramente dulce.",
    usage: "Perfecto para ensaladas coloridas y presentaciones elegantes.",
    category: "Brotes",
    image: "/placeholder.svg?height=400&width=400",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "perifollo",
 sku: "BH-004",
 collection: "Invierno",
    name: "Perifollo",
    description: "Hierba de notas frescas y anisadas, similar al perejil pero con un aroma más delicado.",
    usage: "Se usa en cocina francesa para realzar sabores sin opacarlos.",
    category: "Brotes",
    image: "/perifollo.jpg",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "brote-epazote",
 sku: "BH-005",
 collection: "Invierno",
    name: "Brote de Epazote",
    description: "Versión joven del epazote, con un sabor herbal e intenso.",
    usage: "Ideal para aportar un toque tradicional a guisos, salsas y platillos mexicanos.",
    category: "Brotes",
    image: "/brote_epazote.jpg",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "brote-menta-china",
 sku: "BH-006",
 collection: "Verano",
    name: "Brote de Menta China",
    description: "Hojas tiernas con un aroma refrescante y un sabor ligeramente más especiado que la menta tradicional.",
    usage: "Excelente para infusiones, postres y cocina asiática.",
    category: "Brotes",
    image: "/placeholder.svg",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "hoja-mastuerzo",
 sku: "BH-007",
 collection: "Otoño",
    name: "Hoja de Mastuerzo",
    description: "Hojas pequeñas y tiernas con un sabor picante y ligeramente amargo, similares a la arúgula pero con un toque más intenso.",
    usage: "Perfectas para ensaladas y decoración de platos.",
    category: "Brotes",
    image: "/hoja_mastuerzo.jpg",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "hoja-shizo",
 sku: "BH-008",
 collection: "Otoño",
    name: "Hoja de Shizo",
    description: "Exótica y aromática, con un toque cítrico y especiado." ,
    usage: "Usada en la cocina japonesa para sushi y ensaladas." ,
    category: "Brotes",
    image: "/placeholder.svg?height=400&width=400",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "hojas-limon",
 sku: "BH-009",
 collection: "Otoño",
    name: "Hojas de Limón",
    description: "Aromáticas y frescas, con un toque cítrico sutil." ,
    usage: "Se usan para infusiones, marinados y platillos que buscan un aroma cítrico natural." ,
    category: "Brotes",
    image: "/hoja_lima.jpg",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "hoja-lima-kaffir",
 sku: "BH-010",
 collection: "Otoño",
    name: "Hoja de Lima Kaffir",
    description: "Hojas muy aromáticas con un intenso perfume cítrico, esenciales en la cocina tailandesa." ,
    usage: "Ideales para sopas, currys y platillos exóticos." ,
    category: "Brotes",
    image: "/lima_kaffir.jpg",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "brote-cilantro",
 sku: "BH-011",
 collection: "Primavera",
    name: "Brote de Cilantro",
    description: "Sabor fresco y más intenso que las hojas maduras.",
    usage: "Ideal para guacamole, tacos y ensaladas.",
    category: "Brotes",
    image: "/cilantro-microgreen.jpg",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "brote-chicharo",
 sku: "BH-012",
 collection: "Primavera",
    name: "Brote de Chícharo",
    description: "Dulce y crujiente, con un toque fresco similar al de los guisantes tiernos.",
    usage: "Excelente para ensaladas y woks.",
    category: "Brotes",
    image: "/brote_chicharo.jpg",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "brote-betabel",
 sku: "BH-013",
 collection: "Primavera",
    name: "Brote de Betabel",
    description: "Hojas pequeñas con un sutil dulzor terroso y vibrante color rojo.",
    usage: "Aporta color y sabor a ensaladas y bowls.",
    category: "Brotes",
    image: "/brote_betabel.jpg",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "brote-rabano",
 sku: "BH-014",
 collection: "Primavera",
    name: "Brote de Rábano",
    description: "Picante y vibrante, con un ligero toque especiado.",
    usage: "Perfecto para darle intensidad a sándwiches y tacos.",
    category: "Brotes",
    image: "/brote_rabano.jpg",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "brote-amaranto",
 sku: "BH-015",
 collection: "Primavera",
    name: "Brote de Amaranto",
    description: "Hojas pequeñas con un sabor terroso y un alto contenido de nutrientes.",
    usage: "Ideales para ensaladas y platillos saludables.",
    category: "Brotes",
    image: "/brote_amaranto.jpg",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "brote-arugula",
 sku: "BH-016",
 collection: "Primavera",
    name: "Brote de Arúgula",
    description: "Intenso y picante, con un toque a nuez.",
    usage: "Aporta carácter a ensaladas y pizzas.",
    category: "Brotes",
    image: "/brote_arugula.jpg",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "brote-maiz",
 sku: "BH-017",
 collection: "Verano",
    name: "Brote de Maíz",
    description: "Dulce y jugoso, con un toque crujiente.",
    usage: "Perfecto para ensaladas y guarniciones frescas.",
    category: "Brotes",
    image: "/placeholder.svg?height=400&width=400",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "brote-perejil",
 sku: "BH-018",
 collection: "Primavera",
    name: "Brote de Perejil",
    description: "Sabor intenso y fresco.",
    usage: "Aporta un toque herbal a cualquier platillo.",
    category: "Brotes",
    image: "/brote_perejil.jpg",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "brote-albahaca",
 sku: "BH-019",
 collection: "Primavera",
    name: "Brote de Albahaca",
    description: "Aromático y con notas frescas.",
    usage: "Perfecto para pizzas, pastas y ensaladas.",
    category: "Brotes",
    image: "/brote_albahaca.jpg",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "brote-melon",
 sku: "BH-020",
 collection: "Verano",
    name: "Brote de Melón",
    description: "Dulce y refrescante, con un aroma frutal ligero.",
    usage: "Excelente en ensaladas y decoraciones.",
    category: "Brotes",
    image: "/brote_melon.jpg",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "brote-menta",
 sku: "BH-021",
 collection: "Primavera",
    name: "Brote de Menta",
    description: "Fresco y vibrante, con notas refrescantes.",
    usage: "Ideal para bebidas, postres y ensaladas.",
    category: "Brotes",
    image: "/brote_menta.jpg",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "brote-zanahoria",
 sku: "BH-022",
 collection: "Primavera",
    name: "Brote de Zanahoria",
    description: "Sabor herbáceo con un ligero dulzor.",
    usage: "Ideal para sopas, ensaladas y platos decorativos.",
    category: "Brotes",
    image: "/brote_zanahorita.jpg",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "oxalis",
 sku: "BH-023",
 collection: "Otoño",
    name: "Oxális / Trébol Rojo",
    description: "Ligeramente dulce y terroso, con propiedades nutritivas.",
    usage: "Perfecto para ensaladas y bowls saludables.",
    category: "Brotes",
    image: "/hoja_oxalis.jpg",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "hoja-amaranto",
 sku: "BH-024",
 collection: "Otoño",
    name: "Hoja de Amaranto",
    description: "Terrosa y nutritiva.",
    usage: "Ideal para platillos tradicionales y ensaladas.",
    category: "Brotes",
    image: "/hoja_amaranto.jpg",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "hoja-sorrel",
 sku: "BH-025",
 collection: "Otoño",
    name: "Hoja de Sorrel / Acedera",
    description: "Ácida y refrescante, con un sabor similar al limón.",
    usage: "Perfecta para ensaladas, salsas y pescados.",
    category: "Brotes",
    image: "/hoja_sorrel.jpg",
    price: 35,
    unitOfMeasure: "Domo",
  },

  // --- HORTALIZAS Y HOJAS VERDES (AÑADIDOS) ---
  {
    id: "calabaza-patipan",
 sku: "HV-001",
 collection: "Verano",
    name: "Calabaza Patipán",
    description: "Con su forma de platillo volador, pulpa suave y sabor delicado (la versión amarilla es más dulce)." ,
    usage: "Se puede asar o usar en crudo." ,
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 150,
    unitOfMeasure: "1 kg",
  },
  {
    id: "calabaza-zucchini",
 sku: "HV-002",
 collection: "Verano",
    name: "Calabaza Zucchini",
    description: "Hortaliza de verano. Tiernos, con la versión amarilla siendo más dulce." ,
    usage: "Se puede disfrutar crudo, salteado, asado o a la parrilla.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 150,
    unitOfMeasure: "1 kg",
  },
  {
    id: "betabel-amarillo",
 sku: "HV-003",
 collection: "Verano",
    name: "Betabel Amarillo/Dorado",
    description: "Variedad amarilla con un sabor más suave y menos terroso que el tradicional." ,
    usage: "Perfecto para asados, ensaladas y platos coloridos.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 65,
    unitOfMeasure: "1 kg",
  },
  {
    id: "romanesco",
 sku: "HV-004",
 collection: "Otoño",
    name: "Romanesco",
    description: "Hortaliza verde con patrón fractal. Textura crujiente y sabor suave, ligeramente dulce y menos amargo que el brócoli o la coliflor." ,
    usage: "Ideal al vapor, asado, o en ensaladas.",
    category: "Hortalizas y Hojas Verdes",
    image: "/romanezco.jpg",
    price: 70,
    unitOfMeasure: "1 pza",
  },
  {
    id: "col-rizada",
 sku: "HV-005",
 collection: "Otoño",
    name: "Col Rizada",
    description: "Hojas onduladas y sueltas, formando una cabeza más pequeña y menos compacta. Su sabor es suave y sus hojas más tiernas." ,
    usage: "Ideal para consumir en ensaladas." ,
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 60,
    unitOfMeasure: "1 pza",
  },
  {
    id: "mizuna-verde",
 sku: "HV-006",
 collection: "Otoño",
    name: "Mizuna Verde",
    description: "Hoja verde de origen japonés con sabor suave y un toque de pimienta. Sus hojas dentadas y delicadas son perfectas para ensaladas." ,
    usage: "Aporta una textura ligera y un sabor distintivo a ensaladas." ,
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 115,
    unitOfMeasure: "1 kg",
  },
  {
    id: "mizuna-morada",
 sku: "HV-007",
 collection: "Otoño",
    name: "Mizuna Morada",
    description: "Hojas de tonalidad púrpura profunda. Ofrece un sabor ligeramente más intenso y picante." ,
    usage: "Ideal para ensaladas sofisticadas por su color y sabor.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 115,
    unitOfMeasure: "1 kg",
  },
  {
    id: "col-napa",
 sku: "HV-008",
 collection: "Otoño",
    name: "Col Napa",
    description: "Hojas tiernas y crujientes con sabor suave y dulce. Es un ingrediente esencial en la cocina asiática." ,
    usage: "Esencial en la preparación de kimchi." ,
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 30,
    unitOfMeasure: "1 kg",
  },
  {
    id: "lechuga-escarola",
 sku: "HV-009",
 collection: "Invierno",
    name: "Lechuga Escarola",
    description: "Hojas rizadas y sabor ligeramente amargo." ,
    usage: "Ideal para ensaladas invernales." ,
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 25,
    unitOfMeasure: "1 pza",
  },
  {
    id: "lechuga-frisse-completa",
 sku: "HV-010",
 collection: "Invierno",
    name: "Lechuga Frisse",
    description: "Hojas finamente rizadas y sabor amargo." ,
    usage: "Aporta textura y contraste en ensaladas." ,
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 15,
    unitOfMeasure: "1 pza",
  },
  {
    id: "lechuga-roble-rojo",
 sku: "HV-011",
 collection: "Invierno",
    name: "Lechuga Roble Rojo",
    description: "Hojas lobuladas de color rojo oscuro, con sabor suave y ligeramente dulce." ,
    usage: "Aporta color y dulzura a ensaladas.",
    category: "Hortalizas y Hojas Verdes",
    image: "/lollo_rose.jpg",
    price: 15,
    unitOfMeasure: "1 pza",
  },
  {
    id: "lechuga-orejona",
 sku: "HV-012",
 collection: "Invierno",
    name: "Lechuga Orejona",
    description: "Hojas largas y crujientes de sabor suave. También llamada lechuga romana." ,
    usage: "Perfecta para ensaladas.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 25,
    unitOfMeasure: "1 pza",
  },
  {
    id: "lechuga-sangria",
 sku: "HV-013",
 collection: "Invierno",
    name: "Lechuga Sangría",
    description: "Hojas de tonos rojizos y verdes, caracterizada por su sabor suave y ligeramente amargo." ,
    usage: "Ideal para mezclas de ensaladas por su color y sabor.",
    category: "Hortalizas y Hojas Verdes",
    image: "/sangria.jpg",
    price: 25,
    unitOfMeasure: "1 pza",
  },
  {
    id: "lechuga-corazon-rojo",
 sku: "HV-014",
 collection: "Invierno",
    name: "Lechuga Corazón Rojo",
    description: "Variedad con un corazón de color rojo intenso, ofreciendo un sabor suave y textura crujiente." ,
    usage: "Aporta textura y un punto focal a ensaladas.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 15,
    unitOfMeasure: "1 pza",
  },
  {
    id: "lechuga-mini-italiana",
 sku: "HV-015",
 collection: "Invierno",
    name: "Lechuga Mini Italiana",
    description: "Versión más pequeña de la lechuga italiana, con hojas tiernas y sabor suave." ,
    usage: "Perfecta para porciones individuales o guarniciones.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 15,
    unitOfMeasure: "1 pza",
  },
  {
    id: "lechuga-maple-verde",
 sku: "HV-016",
 collection: "Invierno",
    name: "Lechuga Maple Verde",
    description: "Hojas de color verde brillante y forma similar a la del arce, ofreciendo un sabor suave y textura tierna." ,
    usage: "Ideal para ensaladas delicadas.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 25,
    unitOfMeasure: "1 pza",
  },
  {
    id: "arugula",
 sku: "HV-017",
 collection: "Primavera",
    name: "Arúgula",
    description: "Hojas de sabor intenso y ligeramente picante, con un toque a nuez.",
    usage: "Perfecta para ensaladas, pizzas y acompañamientos frescos.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 60,
    unitOfMeasure: "1 kg",
  },
  {
    id: "albahaca-italiana",
 sku: "HV-018",
 collection: "Primavera",
    name: "Albahaca Italiana",
    description: "Aromática y fresca, con notas dulces y especiadas.",
    usage: "Esencial en la cocina mediterránea, perfecta para pestos, ensaladas y salsas.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 120,
    unitOfMeasure: "1 kg",
  },
  {
    id: "albahaca-morada",
 sku: "HV-019",
 collection: "Primavera",
    name: "Albahaca Morada",
    description: "Variedad vibrante con hojas de color púrpura y un sabor más especiado que la albahaca tradicional.",
    usage: "Ideal para platos asiáticos y decoraciones sofisticadas.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 120,
    unitOfMeasure: "1 kg",
  },
  {
    id: "kale",
 sku: "HV-020",
 collection: "Primavera",
    name: "Berza / Kale",
    description: "Hojas rizadas y robustas, ricas en nutrientes y con un sabor ligeramente terroso.",
    usage: "Excelente para smoothies, ensaladas o salteados.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 50,
    unitOfMeasure: "1 kg",
  },
  {
    id: "espinaca-baby",
 sku: "HV-021",
 collection: "Primavera",
    name: "Espinaca Baby",
    description: "Hojas pequeñas, tiernas y dulces, con un alto contenido de hierro y antioxidantes.",
    usage: "Perfectas para ensaladas, batidos y platillos saludables.",
    category: "Hortalizas y Hojas Verdes",
    image: "/espinaca_granel.jpg",
    price: 120,
    unitOfMeasure: "1 kg",
  },
  {
    id: "espinaca-baby-domo",
 sku: "HV-022",
 collection: "Primavera",
    name: "Espinaca Baby en Domo",
    description: "Hojas pequeñas, tiernas y dulces, con un alto contenido de hierro y antioxidantes. Opción preempaquetada de 250gr por contenedor.",
    usage: "Perfectas para ensaladas, batidos y platillos saludables.",
    category: "Hortalizas y Hojas Verdes",
    image: "/espinaca_baby.jpg",
    price: 35,
    unitOfMeasure: "Domo",
  },
  {
    id: "arugula-baby",
 sku: "HV-023",
 collection: "Primavera",
    name: "Arúgula Baby",
    description: "Versión más tierna y suave de la arúgula tradicional.",
    usage: "Ideal para ensaladas y platos gourmet.",
    category: "Hortalizas y Hojas Verdes",
    image: "/arugula_baby_1.jpg",
    price: 100,
    unitOfMeasure: "1 kg",
  },
  {
    id: "arugula-baby-domo",
 sku: "HV-024",
 collection: "Primavera",
    name: "Arugula Baby en Domo",
    description: "Versión más tierna y suave de la arúgula tradicional. Opción preempaquetada de 250gr por contenedor.",
    usage: "Ideal para ensaladas y platos gourmet.",
    category: "Hortalizas y Hojas Verdes",
    image: "/arugula_baby_2.jpg",
    price: 30,
    unitOfMeasure: "Domo",
  },
  {
    id: "bulbo-hinojo",
 sku: "HV-025",
 collection: "Invierno",
    name: "Bulbo de Hinojo",
    description: "Crujiente y con un delicado sabor anisado.",
    usage: "Ideal para ensaladas frescas, asados o como base para salsas aromáticas.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 70,
    unitOfMeasure: "1 kg",
  },
  {
    id: "pak-choi",
 sku: "HV-026",
 collection: "Verano",
    name: "Pak Choi",
    description: "Variedad pequeña del bok choi, con tallos verdes, con un sabor más tierno y textura crujiente.",
    usage: "Ideal para guarniciones, woks y platos al vapor.",
    category: "Hortalizas y Hojas Verdes",
    image: "/pak_choi.jpg",
    price: 40,
    unitOfMeasure: "1 kg",
  },
  {
    id: "chicharo-japones",
 sku: "HV-027",
 collection: "Verano",
    name: "Chícharo Japonés",
    description: "Vainas tiernas y dulces que pueden comerse enteras. Crujientes y jugosas.",
    usage: "Perfectas para ensaladas, salteados y platillos orientales.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 150,
    unitOfMeasure: "1 kg",
  },
  {
    id: "cebollin",
 sku: "HV-028",
 collection: "Primavera",
    name: "Cebollín",
    description: "Tallos delgados y frescos con un sabor suave a cebolla.",
    usage: "Ideales para decorar platos, hacer salsas o realzar el sabor.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg",
    price: 80,
    unitOfMeasure: "manojo",
  },
  {
    id: "perejil-chino",
 sku: "HV-029",
 collection: "Primavera",
    name: "Perejil Chino",
    description: "Más intenso que el común, con un toque cítrico y ligeramente picante.",
    usage: "Perfecto para decorar salsas, ceviches y platos asiáticos.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 80,
    unitOfMeasure: "1 kg",
  },
  {
    id: "bok-choi",
 sku: "HV-030",
 collection: "Primavera",
    name: "Bok Choi",
    description: "Col china de hojas verdes y tallos blancos jugosos, con un sabor suave y ligeramente dulce.",
    usage: "Perfecto para salteados, sopas y platos asiáticos.",
    category: "Hortalizas y Hojas Verdes",
    image: "/bok_choi.jpg",
    price: 25,
    unitOfMeasure: "1 kg",
  },
  {
    id: "bulbo-hinojo-sin",
 sku: "HV-031",
 collection: "Invierno",
    name: "Bulbo de Hinojo sin Follaje",
    description: "Bulbo crujiente y aromático con sabor anisado y matices dulces. Enfocado en su textura y sabor distintivos.",
    usage: "Aporta profundidad y aroma a platos frescos o asados.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 140,
    unitOfMeasure: "1 kg",
  },
  {
    id: "betabel-sin-follaje",
 sku: "HV-032",
 collection: "Invierno",
    name: "Betabel sin Follaje",
    description: "Raíz de color rojo intenso con un sabor terroso y dulce.",
    usage: "Se puede asar, hervir o consumir crudo en ensaladas.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 90,
    unitOfMeasure: "1 kg",
  },
  {
    id: "ruibarbo",
 sku: "HV-033",
 collection: "Otoño",
    name: "Ruibarbo",
    description: "Tallos alargados de color rojo o rosado con sabor ácido y astringente.",
    usage: "Utilizado en postres como tartas y compotas, mermeladas, o platos salados.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 80,
    unitOfMeasure: "1 kg",
  },
  {
    id: "acelga-colores",
 sku: "HV-034",
 collection: "Verano",
    name: "Acelga de Colores",
    description: "Hojas verdes con tallos de colores vibrantes (rojos, amarillos, naranjas). Sabor suave y ligeramente terroso.",
    usage: "Ideal para salteados y ensaladas coloridas, los tallos aportan una textura crujiente.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 25,
    unitOfMeasure: "1 kg",
  },
  {
    id: "zanahoria-baby-sin",
 sku: "HV-035",
 collection: "Invierno",
    name: "Zanahoria Baby sin Follaje",
    description: "Raíz dulce y crujiente, rica en betacarotenos.",
    usage: "Versátil en la cocina gourmet.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 140,
    unitOfMeasure: "1 kg",
  },
  {
    id: "betabel-candy",
 sku: "HV-036",
 collection: "Verano",
    name: "Betabel Candy",
    description: "Remolacha veteada en tonos rosados y blancos, con un sabor dulce y terroso.",
    usage: "Ideal para ensaladas y platillos decorativos.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 55,
    unitOfMeasure: "1 kg",
  },
  {
    id: "rabano-sandia",
 sku: "HV-037",
 collection: "Primavera",
    name: "Rábano Sandía",
    description: "Exterior blanco y centro rosa vibrante, con un sabor suave y ligeramente picante.",
    usage: "Aporta color y textura a ensaladas y platos frescos.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 100,
    unitOfMeasure: "1 kg",
  },
  {
    id: "zanahoria-baby",
 sku: "HV-038",
 collection: "Verano",
    name: "Zanahoria Baby con Rabo",
    description: "Pequeñas, dulces y crujientes, conservan su tallo verde.",
    usage: "Perfectas para platos gourmet.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 80,
    unitOfMeasure: "1 kg",
  },
  {
    id: "radicchio",
 sku: "HV-039",
 collection: "Invierno",
    name: "Lechuga Radicchio",
    description: "Hojas de un intenso color morado con un sabor ligeramente amargo.",
    usage: "Aporta contraste de color y sabor en ensaladas.",
    category: "Hortalizas y Hojas Verdes",
    image: "/radicchio.jpg",
    price: 50,
    unitOfMeasure: "1 pza",
  },
  {
    id: "lechuga-francesa",
 sku: "HV-041",
 collection: "Invierno",
    name: "Lechuga Francesa",
    description: "Hojas tiernas, mantecosas y de sabor suave.",
    usage: "Ideal para ensaladas delicadas, wraps y acompañamientos ligeros.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 20,
    unitOfMeasure: "1 pza",
  },
  {
    id: "lechuga-francesa-roja",
 sku: "HV-041",
 collection: "Invierno",
    name: "Lechuga Francesa Roja",
    description: "Hojas tiernas, mantecosas y de sabor suave con color rojo vivo.",
    usage: "Ideal para ensaladas delicadas, wraps y acompañamientos ligeros.",
    category: "Hortalizas y Hojas Verdes",
    image: "/francesa_roja.jpg",
    price: 20,
    unitOfMeasure: "1 pza",
  },
];